name: jayben
description: A savings app.

publish_to: "none"

version: 1.00.85+85

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  # firebase_auth: ^5.5.2
  # flutter_secure_storage: ^9.2.4
  # cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_dynamic_links: ^6.1.5
  flutter_countdown_timer: ^4.0.0
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  random_string: ^2.1.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.1.0
  flutter_expanded_tile: ^0.4.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_vibrate: ^1.3.0
  just_audio: ^0.9.36
  screenshot: ^3.0.0
  # liquid_swipe: ^2.1.1
  slider_button: ^2.0.0
  # responsive_framework: ^1.1.1
  responsive_framework: ^0.2.0
  flutter_screenutil: ^5.3.1
  provider: ^6.0.5
  awesome_notifications: ^0.10.1
  shared_preferences_foundation:
  country_pickers: ^3.0.1
  country_data: ^0.0.2
  uuid: ^4.4.0
  google_fonts: ^6.1.0
  webview_flutter: ^4.2.3
  package_info_plus: ^8.3.0
  # supabase_flutter: ^1.10.25
  supabase_flutter: ^2.1.0
  encryptor: ^0.0.1
  rounded_background_text: ^0.6.0
  timeago: ^3.2.2
  # dart_openai: ^4.0.0
  # ussd_advanced: ^1.1.0
  device_info_plus: ^11.3.3
  # contacts_service: ^0.6.3
  fast_contacts: ^4.0.0
  # flutter_sms: ^2.3.3
  mobile_number: ^3.0.0
  url_launcher: ^6.2.6
  signed_spacing_flex: ^1.1.0
  expandable: ^5.0.1
  dropdown_button2: ^2.3.9
  get_ip_address: ^0.0.6
  platform_device_id: ^1.0.1
  share_plus: ^10.1.4
  video_compress: ^3.1.2
  video_player: ^2.8.1
  like_button: ^2.0.5
  audio_video_progress_bar: ^2.0.1
  email_validator: ^3.0.0
  audio_service: ^0.18.13
  nfc_manager: ^3.3.0
  shimmer: ^3.0.0

  # ==================================

  cupertino_icons: ^1.0.2
  # flutter_secure_storage_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
